### ISSUE TITLE
Module 3, OOP oef 1.2 persoon

### ISSUE THREAD

**Issue by justapyromaniac** [AP-TI-2018-2019/AP_2018-2019#4]
bij de methode om de leeftijd te berekenen kan je optimaliseren, klein verschil maar toch
  public int Leeftijd()
        {
            DateTime vandaag = DateTime.Today;
            int leeftijd = DateTime.Now.Year - Geboortedatum.Year;
            if (vandaag < new DateTime(vandaag.Year, Geboortedatum.Month, Geboortedatum.Day))
                leeftijd--;
            return leeftijd;
        }
kan sneller zo:
 public int Leeftijd()
        {
            DateTime vandaag = DateTime.Today;
            int leeftijd = vandaag.Year - Geboortedatum.Year;
            if (vandaag < new DateTime(vandaag.Year, Geboortedatum.Month, Geboortedatum.Day))
                leeftijd--;
            return leeftijd;
        }

**Comment by mixxamm** [comment]
Bedankt voor je opmerking!

Ik heb nog een kleine wijziging doorgevoerd om de code nog korter te maken:
```csharp
public int BerekenLeeftijd(DateTime datum)
        {
            int leeftijd = datum.Year - Geboortedatum.Year;
            if (datum.DayOfYear < Geboortedatum.DayOfYear)
                leeftijd--;
            return leeftijd;
        }
```
Zoals je ziet kan je gewoon .DayOfYear gebruiken, op die manier hoef je geen nieuw DateTime object te maken.

Ik verander het zo meteen in de oefeningen.

**Comment by mixxamm** [comment]
Sorry, had niet gezien dat je het had over oefening 1.2.
Maar die kan je ook inkorten door gebruik te maken van .DayOfYear.
```csharp
public int Leeftijd()
        {
            DateTime vandaag = DateTime.Today;
            int leeftijd = vandaag.Year - Geboortedatum.Year;
            if (vandaag.DayOfYear < Geboortedatum.DayOfYear)
                leeftijd--;
            return leeftijd;
        }
```
Bij deze ook alle oefeningen van les 1 aangepast.
